FROM bitnami/mariadb-galera:latest
COPY ./data/node1 /bitnami/mariadb
#RUN chmod -R 777 /bitnami/mariadb
#RUN useradd -u 1001 mariadb-bitnami
#RUN chown -R mariadb-bitnami:mariadb-bitnami /bitnami/mariadb